// Generated by CoffeeScript 1.7.1
var _;

_ = {};

(function() {
  _.identity = function(val) {};
  _.first = function(array, n) {};
  _.last = function(array, n) {};
  _.each = function(collection, iterator) {};
  _.indexOf = function(array, target) {};
  _.filter = function(collection, test) {};
  _.reject = function(collection, test) {};
  _.uniq = function(array) {};
  _.map = function(collection, iterator) {};
  _.pluck = function(collection, key) {};
  _.invoke = function(collection, functionOrKey, args) {};
  _.reduce = function(collection, iterator, accumulator) {};
  _.contains = function(collection, target) {};
  _.every = function(collection, iterator) {};
  _.some = function(collection, iterator) {};
  _.extend = function(obj) {};
  _.defaults = function(obj) {};
  _.once = function(func) {};
  _.memoize = function(func) {};
  _.delay = function(func, wait) {};
  _.shuffle = function(array) {};
  _.sortBy = function(collection, iterator) {};
  _.zip = function() {};
  _.flatten = function(nestedArray, result) {};
  _.intersection = function() {};
  _.difference = function(array) {};
  _.throttle = function(func, wait) {};
})();
